### PR TITLE
store all apple followers data

### LINKED ISSUE #116: followers apple is wrong, gained lost is missing

### PR DESCRIPTION
**Pull request by woolfg**
fix #116

### CODE REVIEW

File: db_schema/queries/v1/reportApplePodcastBasisMetrics.sql
Comment (mre) [inline db_schema/queries/v1/reportApplePodcastBasisMetrics.sql:1]: Should we call it `BaseMetrics` instead of `BasisMetrics`? The latter sounds German to me.

File: db_schema/queries/v1/reportApplePodcastBasisMetrics.sql [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+    atl_date >= @start
+    AND atl_date <= @end
+    AND account_id = @podcast_id
+  GROUP BY
+    account_id
+),
+followers_start AS (
+  SELECT
+    account_id as podcast_id,
+    atf_totalfollowers-atf_totalunfollowers as apple_followers
```
Comment (mre) [inline db_schema/queries/v1/reportApplePodcastBasisMetrics.sql:21]: At first, I thought the dash belongs to the field name.
Shall we at spaces?

```suggestion
    atf_totalfollowers - atf_totalunfollowers as apple_followers
```

File: db_schema/queries/v1/reportApplePodcastBasisMetrics.sql [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+  FROM
+    appleTrendsPodcastFollowers
+  WHERE
+    atf_date = @start
+    AND account_id = @podcast_id 
+),
+followers_end AS (
+  SELECT
+    account_id as podcast_id,
+    atf_totalfollowers-atf_totalunfollowers as apple_followers
```
Comment (mre) [inline db_schema/queries/v1/reportApplePodcastBasisMetrics.sql:31]: same here

File: src/api/connectors/AppleConnector.ts [hunk 3]
```diff
@@ -90,35 +91,48 @@ class AppleConnector implements ConnectorHandler {
...
-                if (dayElem) {
-                    dayElem.gained = curr[1]
-                    dayElem.lost = curr[1]
-                }
-                return prev
-            }, days)
+            followerData = payloadData.followerGrowthTrends.reduce(
+                (prev, curr) => {
+                    // as gained/lost is the difference between the date and the next date
+                    // we want to store it together with the next day
```
Comment (mre) [inline src/api/connectors/AppleConnector.ts:118]: That comment confuses me. Shouldn't it be
```suggestion
                    // we want to store it together with the previous day
```
? 🤔 Depends on how you look at it, I guess.

File: tests/api_e2e/anchor.test.js [hunk 4]
```diff
@@ -9,7 +9,6 @@ const anchorPlaysPayload = require('../../fixtures/anchorPlays.json')
 const anchorPlaysByAgeRangePayload = require('../../fixtures/anchorPlaysByAgeRange.json')
 const anchorPlaysByAppPayload = require('../../fixtures/anchorPlaysByApp.json')
 const anchorPlaysByDevicePayload = require('../../fixtures/anchorPlaysByDevice.json')
-const anchorPlaysByEpisodePayload = require('../../fixtures/anchorPlaysByEpisode.json')
```
Comment (mre) [inline tests/api_e2e/anchor.test.js:12]: Wondering why this test was removed. Is it related to the rest of the changes? 🤔

File: src/api/connectors/AppleConnector.ts (hunk 3 above)
Comment (woolfg) [reply src/api/connectors/AppleConnector.ts:118]: yup, but gained has to be stored with the next day

File: tests/api_e2e/anchor.test.js (hunk 4 above)
Comment (woolfg) [reply tests/api_e2e/anchor.test.js:12]: #117
